ifneq (,$(filter gnrc_netdev_default ipv6_addr,$(USEMODULE)))
  USEMODULE += netif
  USEMODULE += cc2538_rf
  USEMODULE += netdev_ieee802154
  

endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += saul_adc
endif
