include ../Makefile.tests_common

#FEATURES_REQUIRED = periph_i2c

USEMODULE += ph_oem
#USEMODULE += xtimer
#USEMODULE += fmt

## set default device parameters in case they are undefined
#PH_OEM_PARAM_I2C  ?= I2C_DEV\(0\)
#PH_OEM_PARAM_ADDR ?= 0x65
#
## export parameters
#CFLAGS += -DPH_OEM_PARAM_I2C=$(PH_OEM_PARAM_I2C)
#CFLAGS += -DPH_OEM_PARAM_ADDR=$(PH_OEM_PARAM_ADDR)

include $(RIOTBASE)/Makefile.include
